const { jsPDF } = require("jspdf");
require("jspdf-autotable");

/**
 * Generates a professional SWM Impact Report
 * @param {Array} collectionData - Array of collection objects
 * @param {Object} adminInfo - Name of the generating admin
 */
const generateSWMReport = (collectionData, adminInfo) => {
  const doc = new jsPDF();
  const date = new Date().toLocaleDateString();

  // 1. Header Section
  doc.setFontSize(20);
  doc.setTextColor(46, 125, 50); // Theme Green
  doc.text("SMART WASTE MANAGEMENT SYSTEM", 14, 22);
  
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text("Official Monthly Operational & Impact Report", 14, 30);
  doc.text(`Generated By: ${adminInfo.name}`, 14, 36);
  doc.text(`Date: ${date}`, 14, 42);

  // 2. Summary Logic
  const totalWeight = collectionData.reduce((acc, curr) => acc + (curr.actualWeight || 0), 0);
  const completedTasks = collectionData.filter(c => c.status === 'Collected').length;

  doc.setFontSize(12);
  doc.setTextColor(0);
  doc.text(`Total Waste Collected: ${totalWeight} kg`, 14, 55);
  doc.text(`Successful Pickups: ${completedTasks}`, 14, 62);

  // 3. Data Table
  const tableRows = collectionData.map(item => [
    new Date(item.createdAt).toLocaleDateString(),
    item.resident?.name || 'N/A',
    item.address?.zone?.toUpperCase() || 'N/A',
    item.wasteType,
    `${item.actualWeight || 0}kg`,
    item.status
  ]);

  doc.autoTable({
    startY: 70,
    head: [['Date', 'Resident', 'Zone', 'Waste Type', 'Weight', 'Status']],
    body: tableRows,
    headStyles: { fillStyle: [46, 125, 50] }, // Matching system theme
    alternateRowStyles: { fillColor: [240, 245, 240] },
  });

  // 4. Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.text(`Page ${i} of ${pageCount} - SWMS Digital Portal`, 14, doc.internal.pageSize.height - 10);
  }

  return doc.output('arraybuffer'); // Return as buffer for Express to send
};

module.exports = { generateSWMReport };